-- Simplify document_app_filing_rule and add the ISO 61355 doc-number counter.
--
-- The new POST /api/file endpoint mints document numbers in line with the
-- ISO 61355 reference designation pattern: <reference>-<DCC>-<serial>, where
-- reference is a 5-digit project number (or '00000' for non-project docs) and
-- serial is per-(reference, DCC).
--
-- That design eliminates per-app filename templates, path templates, arbitrary
-- meta blob substitution, and meta-keyed dedup rules. Filing rules now just
-- declare whether a project number is required for a given (app, doc type)
-- combination — everything else is generated by the doc service.

-- 1. document_app_filing_rule slims down --------------------------------------

alter table document_app_filing_rule
  drop column required_meta,
  drop column path_template,
  drop column filename_template,
  drop column dedup_rules;

alter table document_app_filing_rule
  add column requires_project_number boolean not null default true;

-- 2. ISO doc-number counter --------------------------------------------------
-- Atomic per-(reference, DCC) sequence. Reference is the 5-digit project
-- number for project-bound docs, '00000' for non-project. DCC is identified by
-- (iso_tech_area_id, iso_subclass_id). Mint via UPSERT returning last_serial.

create table if not exists iso61355_doc_number_counter (
  reference         text        not null,
  iso_tech_area_id  int         not null references iso61355_technical_area(id),
  iso_subclass_id   int         not null references iso61355_subclass(id),
  last_serial       int         not null default 0,
  updated_at        timestamptz not null default now(),

  primary key (reference, iso_tech_area_id, iso_subclass_id)
);

-- 3. document_incoming_scan: project_number + doc_number ---------------------
-- New columns are nullable so legacy rows (scanner, matl-cert) stay valid
-- until those flows migrate to the new endpoint.

alter table document_incoming_scan
  add column if not exists project_number text,
  add column if not exists doc_number     text;

create index if not exists idx_document_incoming_scan_project_number
  on document_incoming_scan (project_number);

-- doc_number is unique by construction (counter + project + DCC). Partial
-- unique index lets legacy rows keep doc_number NULL without conflicts.
create unique index if not exists uniq_document_incoming_scan_doc_number
  on document_incoming_scan (doc_number)
  where doc_number is not null;
